### PR TITLE
Initial work

### PR DESCRIPTION
**Pull request by forabi**
## Tasks
* [ ] Create deployment pipeline
* [ ] Configure Travis
* [x] Configure S3 backend for Terraform state storage
  * [ ] ~Manage Terraform state backend with Terraform?~ (complicated)
* [x] VPC, AZs, security groups, public and private subnets
* [ ] Database
  * [x] Cluster
  * [x] Master instance
  * [ ] Alarms
    * [x] Monitoring role
    * [x] SNS topic
  * [x] Secrets Manager secret
* [x] Logging infrastructure
  * [x] S3 bucket
  * [x] SQS queues
  * [x] SNS notification
* [x] Photos infrastructure
  * [x] Source S3 bucket
  * [x] Target S3 bucket
  * [x] CloudFront distribution
  * [ ] Fine tune caching
* [ ] Route 53 hosted zones if possible
  * [x] Import or use as `data`
  * [x] Create records for `photos.hollowverse.com` and `photos-dev.hollowverse.com`
  * [ ] Set up records for `hollowverse.com`, `www.hollowverse.com`, `api.hollowverse.com`... etc.
* [x] Bastion host
  * [x] Allow access to database
  * [x] Generate new SSH keypair
* [x] Test that the API Lambda can access the newly created database instance
* [x] Test that `process-image` works with the newly created buckets

### CODE REVIEW

**Comment by wholesomedev** [comment]
What do you think about renaming this repo to either just `cloudformations` or `infra-templates` (for infrastructure templates)?

**Comment by forabi** [comment]
> What do you think about renaming this repo to either just `cloudformations` or `infra-templates`?

I'm using AWS terminology. A *CloudFormation template* refers to the JSON/YAML file. A *Stack* is created from a template. A Stack is a group of *Resources*.

I think it's better to stick to the official terminology.

**Comment by wholesomedev** [comment]
👍

**Comment by forabi** [comment]
I'm having problems with the Aurora module. The resources are created successfully, but when I re-run the apply command it destroys the database and creates a new one. I guess I should just define the resources myself instead of using the Aurora module.

**Comment by forabi** [comment]
@wholesomedev I'm starting to wonder whether it would be viable to set up CI for infrastructure. This [article](https://blog.gruntwork.io/how-to-manage-terraform-state-28f5697e68fa) outlines many of the challenges around using infrastructure as code for teams, with state locking and testing changes in a staging environment being the primary problematic areas.

Another challenge that I think would prevent us from using CI is that the change plan must be reviewed manually. It's easy to destroy data with the declarative approach to infrastructure management. A simple change in a computed cluster ID, or in the availability zones of a database cluster could force the creation of new resources, destroying the databases along the way. Of course, `terraform plan` shows exactly what's going to happen, but how would we make that work with CI? How would we automate creation of new resources that we consider safe and prevent those which are not safe?

**Comment by forabi** [comment]
Things are looking good so far! I'm adding infrastructure that powers `photos.hollowverse.com`. This is going to be a bit tricky as we first need to de-associate that subdomain from the already existing (unmanaged) CF distribution.

**Comment by forabi** [comment]
We'll also need to deploy development versions of `process-image` and `api` to make sure these can work with the new infrastructure.

**Comment by forabi** [comment]
I've configured the bastion host and confirmed that we can access the database in the private subnet via the bastion using SSH! This is really cool!

**Comment by forabi** [comment]
I deployed a production copy of the entire infrastructure from my computer for now. I'm going to merge this and continue the remaining tasks in later PRs.

**Review by wholesomedev — COMMENTED** [review]
Whoa. This seems super cool!

I can tell that lot of research and figuring out have gone into creating this. It's dense, but very well organized.

I like that our infrastructure is declaratively defined like this. And the ability to spin up a complete infrastructure for different stage environments is great to have.

This will also make our configurations visible outside of AWS UI, help with documentation, and make it easier to get a complete picture of our system (though I'll need to read up on Terraform syntax :D)

Great work in figuring this stuff out and making it happen!

**Pull request merged**
